RandomGame/RandomGame.MVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RandomGame.BusinessLogicLayer.Abstract;
using RandomGame.Entity.DTO;
using RandomGame.Entity.POCO;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;

namespace RandomGame.MVC.Controllers
{
    public class CartController : Controller
    {
        UserManager<AppUser> userManager;
        ICartService cartService;
        public CartController(UserManager<AppUser> userManager, ICartService cartService)
        {
            this.userManager = userManager;
            this.cartService = cartService;
        }
    
        public IActionResult Index()
        {
            var user = userManager.FindByNameAsync(User.Identity.Name);
            HttpClient client = new HttpClient();
            string apiUrl = "https://localhost:44362/api/Cart/GetCartById/" + user.Result.Id;
            //Uri uri = new Uri(apiUrl);
            WebClient webClient = new WebClient();
            webClient.Encoding = System.Text.Encoding.UTF8;
            string sonuc = webClient.DownloadString(apiUrl);
            List<CartDTO> result = JsonConvert.DeserializeObject<List<CartDTO>>(sonuc);
            return View(result);
        }
        
        public IActionResult AddToCart(int gameId,int count)
        {
            var user = userManager.FindByNameAsync(User.Identity.Name);
            var cart = new CartDTO { UserId = user.Result.Id, GameId = gameId, Quantity = count };
            string apiUrl = "https://localhost:44362/api/Cart/AddCart";
            HttpClient client = new HttpClient();
            var result = JsonConvert.SerializeObject(cart);
            StringContent content = new StringContent(result, System.Text.Encoding.UTF8, "application/json");
            var sonuc = client.PostAsync(apiUrl, content);
            var rst = sonuc.Result.Content.ReadAsStringAsync();
            return Ok(rst.Result);
            
        }

        public IActionResult DeleteCartByID(int gameId)
        {
            var user = userManager.FindByNameAsync(User.Identity.Name);
            HttpClient client = new HttpClient();
            string apiUrl = "https://localhost:44362/api/Cart/DeleteCart/" + user.Result.Id+"/"+gameId;
            //Uri uri = new Uri(apiUrl);
            WebClient webClient = new WebClient();
            webClient.Encoding = System.Text.Encoding.UTF8;
            string sonuc = webClient.DownloadString(apiUrl);
            return RedirectToAction("Index");
        }

    }
}

RandomGame/RandomGame.MVC/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RandomGame.MVC.Models;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;

namespace RandomGame.MVC.Controllers
{
	public class GameController : Controller
	{
		public IActionResult Detail(int gameId)
		{
            HttpClient client = new HttpClient();
            string apiUrl = "https://localhost:44362/Game/GetGameById/"+gameId;
            //Uri uri = new Uri(apiUrl);
            WebClient webClient = new WebClient();
            webClient.Encoding = System.Text.Encoding.UTF8;
            string sonuc = webClient.DownloadString(apiUrl);
            GameModel result = JsonConvert.DeserializeObject<GameModel>(sonuc);
            return View(result);
		}
	}
}

RandomGame/RandomGame.MVC/Views/Cart/Index.cshtml
@model List<CartDTO>
<!-- page title -->
<section class="section section--first section--last section--head" data-bg="img/bg.jpg">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="section__wrap">
					<!-- section title -->
					<h2 class="section__title">Checkout</h2>
					<!-- end section title -->
					<!-- breadcrumb -->
					<ul class="breadcrumb">
						<li class="breadcrumb__item"><a href="index.html">Home</a></li>
						<li class="breadcrumb__item breadcrumb__item--active">Checkout</li>
					</ul>
					<!-- end breadcrumb -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- end page title -->
<!-- section -->
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-12 col-lg-8">
				<!-- cart -->
				<div class="cart">
					<div class="table-responsive">
						<table class="cart__table">
							<thead>
								<tr>
									<th><a href="#">Product <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.71,10.21,12,7.91l2.29,2.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42l-3-3a1,1,0,0,0-1.42,0l-3,3a1,1,0,0,0,1.42,1.42Zm4.58,4.58L12,17.09l-2.29-2.3a1,1,0,0,0-1.42,1.42l3,3a1,1,0,0,0,1.42,0l3-3a1,1,0,0,0-1.42-1.42Z" /></svg></a></th>
									<th><a href="#" class="active">Title <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17,13.41,12.71,9.17a1,1,0,0,0-1.42,0L7.05,13.41a1,1,0,0,0,0,1.42,1,1,0,0,0,1.41,0L12,11.29l3.54,3.54a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29A1,1,0,0,0,17,13.41Z" /></svg></a></th>
									<th><a href="#">Platform <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.71,10.21,12,7.91l2.29,2.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42l-3-3a1,1,0,0,0-1.42,0l-3,3a1,1,0,0,0,1.42,1.42Zm4.58,4.58L12,17.09l-2.29-2.3a1,1,0,0,0-1.42,1.42l3,3a1,1,0,0,0,1.42,0l3-3a1,1,0,0,0-1.42-1.42Z" /></svg></a></th>
									<th><a href="#">Price <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.71,10.21,12,7.91l2.29,2.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42l-3-3a1,1,0,0,0-1.42,0l-3,3a1,1,0,0,0,1.42,1.42Zm4.58,4.58L12,17.09l-2.29-2.3a1,1,0,0,0-1.42,1.42l3,3a1,1,0,0,0,1.42,0l3-3a1,1,0,0,0-1.42-1.42Z" /></svg></a></th>
									<th></th>
								</tr>
							</thead>

							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											<div class="cart__img">
												<img src="@item.ImageURl" alt="">
											</div>
										</td>
										<td><a asp-controller="Game" asp-action="Detail" asp-route-gameId="@item.GameId">@item.GameName</a></td>
										<td>PC</td>
										<td><span class="cart__price">$@item.Price</span></td>
										<td>
											<a asp-controller="Cart" asp-action="DeleteCartByID" asp-route-gameId="@item.GameId"><button class="cart__delete" type="button"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><line x1='368' y1='368' x2='144' y2='144' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px' /><line x1='368' y1='144' x2='144' y2='368' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px' /></svg></button></a></td>
									</tr>
								}
							</tbody>
						</table>
					</div>

					<div class="cart__info">
						<div class="cart__total">
							<p>Total:</p>
							<span>$27.98</span>
						</div>

						<div class="cart__systems">
							<i class="pf pf-visa"></i>
							<i class="pf pf-mastercard"></i>
							<i class="pf pf-paypal"></i>
						</div>
					</div>
				</div>
				<!-- end cart -->
			</div>

			<div class="col-12 col-lg-4">
				<!-- checkout -->
				<form action="#" class="form form--first form--coupon">
					<input type="text" class="form__input" placeholder="Coupon code">
					<button type="button" class="form__btn">Apply</button>
				</form>
				<!-- end checkout -->
				<!-- checkout -->
				<form action="#" class="form">
					<input type="text" name="name" class="form__input" placeholder="John Doe">
					<input type="text" name="email" class="form__input" placeholder="gg@template.buy">
					<input type="text" name="phone" class="form__input" placeholder="+1 234 567-89-00">
					<select name="systems" class="form__select">
						<option value="visa">Visa</option>
						<option value="mastercard">Mastercard</option>
						<option value="paypal">Paypal</option>
					</select>
					<span class="form__text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.</span>
					<button type="button" class="form__btn">Complete</button>
				</form>
				<!-- end checkout -->
			</div>
		</div>
	</div>
</div>
<!-- end section -->
<!-- section -->
<div class="section section--last">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="partners owl-carousel">
					<a href="#" class="partners__img">
						<img src="img/partners/3docean-light-background.png" alt="">
					</a>

					<a href="#" class="partners__img">
						<img src="img/partners/activeden-light-background.png" alt="">
					</a>

					<a href="#" class="partners__img">
						<img src="img/partners/audiojungle-light-background.png" alt="">
					</a>

					<a href="#" class="partners__img">
						<img src="img/partners/codecanyon-light-background.png" alt="">
					</a>

					<a href="#" class="partners__img">
						<img src="img/partners/photodune-light-background.png" alt="">
					</a>

					<a href="#" class="partners__img">
						<img src="img/partners/themeforest-light-background.png" alt="">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end section -->